fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
