home:
    path:     /
    defaults: { _controller: SiteBundle:Site:index }

#Overriding FOSUser NE PAS TOUCHER
fos_user_profile_show:
    path:     /mon-profil
    defaults: { _controller: FOSUserBundle:Profile:show }
    methods:  [GET]
fos_user_profile_edit:
    path:     /editer-mon-profil
    defaults: { _controller: FOSUserBundle:Profile:edit }
    methods:  [GET]


new_photo:
    path:     /photo/new
    defaults: { _controller: SiteBundle:Photo:newPhoto }

my_photos:
    path:     /mes-photos
    defaults: { _controller: SiteBundle:Photo:myPhotos }

one_photo:
    path:     /photo/{id}
    defaults: { _controller: SiteBundle:Photo:onePhoto }
    requirements:
        id: '\d+'

delete_photo:
    path:     /photo/delete/{id}
    defaults: { _controller: SiteBundle:Photo:deletePhoto }
    requirements:
        id: '\d+'

new_appareil:
    path:     /appareil/new
    defaults: { _controller: SiteBundle:Site:newAppareil }

delete_appareil:
    path:     /appareil/delete/{id}
    defaults: { _controller: SiteBundle:Site:deleteAppareil }
    requirements:
        id: '\d+'

my_appareils:
    path:     /mes-appareils
    defaults: { _controller: SiteBundle:Site:myAppareils }
