home:
    path:     /
    defaults: { _controller: SiteBundle:Site:index }

#Overriding FOSUser NE PAS TOUCHER
fos_user_profile_show:
    path:     /mon-profil
    defaults: { _controller: FOSUserBundle:Profile:show }
    methods:  [GET]
fos_user_profile_edit:
    path:     /editer-mon-profil
    defaults: { _controller: FOSUserBundle:Profile:edit }
    methods:  [GET]


new_photo:
    path:     /photo/new
    defaults: { _controller: SiteBundle:Photo:newPhoto }

ajax_photo_create:
    path:     /ajax/photo/create
    defaults: { _controller: SiteBundle:Ajax:create }

my_photos:
    path:     /mes-photos
    defaults: { _controller: SiteBundle:Photo:myPhotos }

debug_photo:
    path:     /debug/{id}
    defaults: { _controller: SiteBundle:Site:debugPhoto }
    requirements:
        id: '\d+'

one_photo:
    path:     /photo/{id}
    defaults: { _controller: SiteBundle:Photo:onePhoto }
    requirements:
        id: '\d+'

delete_photo:
    path:     /photo/delete/{id}
    defaults: { _controller: SiteBundle:Photo:deletePhoto }
    requirements:
        id: '\d+'

new_appareil:
    path:     /appareil/new
    defaults: { _controller: SiteBundle:Site:newAppareil }

delete_appareil:
    path:     /appareil/delete/{id}
    defaults: { _controller: SiteBundle:Site:deleteAppareil }
    requirements:
        id: '\d+'

my_stuff:
    path:     /mes-appareils
    defaults: { _controller: SiteBundle:Site:myStuff }

new_lens:
    path:     /lens/new
    defaults: { _controller: SiteBundle:Site:newLens }

delete_lens:
    path:     /lens/delete/{id}
    defaults: { _controller: SiteBundle:Site:deleteLens }
    requirements:
        id: '\d+'

new_tag:
    path:     /tag/new
    defaults: { _controller: SiteBundle:Tag:newTag }

delete_tag:
    path:     /tag/delete/{id}
    defaults: { _controller: SiteBundle:Tag:deleteTag }
    requirements:
        id: '\d+'

listing_tag:
    path:     /tags
    defaults: { _controller: SiteBundle:Tag:listingTag }