home:
    path:     /
    defaults: { _controller: SiteBundle:Site:index }

new_photo:
    path:     /photo/new
    defaults: { _controller: SiteBundle:Photo:newPhoto }

my_photos:
    path:     /me/photos
    defaults: { _controller: SiteBundle:Photo:myPhotos }

one_photo:
    path:     /photo/{id}
    defaults: { _controller: SiteBundle:Photo:onePhoto }
    requirements:
        id: '\d+'

delete_photo:
    path:     /photo/delete/{id}
    defaults: { _controller: SiteBundle:Photo:deletePhoto }
    requirements:
        id: '\d+'

new_appareil:
    path:     /appareil/new
    defaults: { _controller: SiteBundle:Site:newAppareil }

delete_appareil:
    path:     /appareil/delete/{id}
    defaults: { _controller: SiteBundle:Site:deleteAppareil }
    requirements:
        id: '\d+'

my_appareils:
    path:     /me/appareils
    defaults: { _controller: SiteBundle:Site:myAppareils }